//
// Created by Marco on 31/12/17.
//

#ifndef BUBBLEREGIONSFLOORPLANNER_FLOORTPLANNINGMANGERSTATE_H
#define BUBBLEREGIONSFLOORPLANNER_FLOORTPLANNINGMANGERSTATE_H

enum FloortplanningMangerState{
    START,
    WAITING_FOR_WIRE_STABILITY,
    WIRE_STABILITY_IMPROVEMENT,
    SEARCH_PLACEM,
    END
};


#endif //BUBBLEREGIONSFLOORPLANNER_FLOORTPLANNINGMANGERSTATE_H
